<?php


/**
 * Skeleton subclass for representing a row from the 'casa' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jul 20 20:04:51 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Casa extends BaseCasa {

	/**
	 * Initializes internal state of Casa object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
	
	public function getFullDireccion() {
        return sprintf("%s, %s, %s, %s",  $this->direccion, $this->colonia, $this->cp, $this->ciudad);
    }

    public function get_Nombre(){
        return sprintf("%s %s %s",  $this->getNombre(),$this->getAPaterno(), $this->getAMaterno());
    }
    public function get_ministerio(){
        return sprintf("%s",  MinisterioPeer::retrieveByPk($this->ministerio));
    }
    

} // Casa
