<?php


/**
 * Skeleton subclass for representing a row from the 'iglesia' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jul 20 20:04:51 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Iglesia extends BaseIglesia {


public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

	public function getFullDireccion() {
        return sprintf("%s, %s, %s, %s%s, %s",  $this->direccion, $this->colonia, $this->cp, $this->ciudad, $this->estado, $this->pais);
    } 
    public function getDomicilio() {
        return sprintf("%s, Col. %s, CP %s",  $this->direccion, $this->colonia, $this->cp);
    } 
    public function getLocalizacion() {
        return sprintf(" Municipio de %s, %s, %s",  $this->ciudad, $this->estado, $this->pais);
    } 
     public function get_Nombre(){
        return sprintf("%s %s %s",  $this->getNombrePastor(),$this->getAPaterno(), $this->getAMaterno());
    }

} // Iglesia
