<?php


/**
 * Skeleton subclass for performing query and update operations on the 'ministerio' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jul 20 20:04:50 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MinisterioPeer extends BaseMinisterioPeer {

} // MinisterioPeer
